// Auth Action Types
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const CLEAR_REGISTER_ERRORS = 'CLEAR_REGISTER_ERRORS';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

// Admin Action Types
export const FETCH_CALCULATIONS_REQUEST = 'FETCH_CALCULATIONS_REQUEST';
export const FETCH_CALCULATIONS_SUCCESS = 'FETCH_CALCULATIONS_SUCCESS';
export const FETCH_CALCULATIONS_FAILURE = 'FETCH_CALCULATIONS_FAILURE';

export const CREATE_CALCULATION_SUCCESS = 'CREATE_CALCULATION_SUCCESS';
export const EDIT_CALCULATION_SUCCESS = 'EDIT_CALCULATION_SUCCESS';
export const DELETE_CALCULATION_SUCCESS = 'DELETE_CALCULATION_SUCCESS';

// Calculator Action Types
export const SET_CALCULATOR_DATA = 'SET_CALCULATOR_DATA';
export const CALCULATE_LOAN_SUCCESS = 'CALCULATE_LOAN_SUCCESS';
export const CALCULATE_LOAN_FAILURE = 'CALCULATE_LOAN_FAILURE';

export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';

// Добавьте другие action types здесь...
